import { RouteConfig, ROUTER_DIRECTIVES } from 'angular2/router';
import { Component } from 'angular2/core';
import { SidebarComponent } from '../sidebar/sidebar.component';
import { FrontPageComponent } from '../content/front-page.component';
import { IntroductionComponent } from '../content/introduction.component';
import { AboutOnlineHelpComponent } from '../content/about-online-help.component';
import { NavigatingOnlineHelpComponent } from '../content/navigating-online-help.component';

@Component({
  selector: 'my-app',
  templateUrl: '/app/main/main.html',
  directives: [
    ROUTER_DIRECTIVES,
    SidebarComponent
  ]
})

@RouteConfig([
  {path: '/start/:topic', name: 'FrontPage', component: FrontPageComponent, useAsDefault: true},
  {path: '/introduction', name: 'Introduction', component: IntroductionComponent},
  {path: '/about-online-help', name: 'AboutOnlineHelp', component: AboutOnlineHelpComponent},
  {path: '/navigating-online-help', name: 'NavigatingOnlineHelp', component: NavigatingOnlineHelpComponent},
  {path: '/revision-history', name: 'RevisionHistory', component: AboutOnlineHelpComponent},
  {path: '/additional-resources', name: 'AdditionalResources', component: AboutOnlineHelpComponent},
  {path: '/accessing-rio', name: 'AccessingRIO', component: AboutOnlineHelpComponent},
  {path: '/navigating-rio', name: 'NavigatingRIO', component: AboutOnlineHelpComponent},
  {path: '/accessing-entities', name: 'AccessingEntities', component: AboutOnlineHelpComponent},
  {path: '/logging-out-session-timeout', name: 'LoggingOutSessionTimeout', component: AboutOnlineHelpComponent},
  {path: '/application-features-tools-overview', name: 'ApplicationFeaturesToolsOverview', component: AboutOnlineHelpComponent},
  {path: '/accessing-entity-types', name: 'AccessingEntityTypes', component: AboutOnlineHelpComponent},
  {path: '/using-search-function', name: 'UsingSearchFunction', component: AboutOnlineHelpComponent},
  {path: '/using-service-path-sidebar', name: 'UsingServicePathSidebar', component: AboutOnlineHelpComponent},
  {path: '/using-tabs', name: 'UsingTabs', component: AboutOnlineHelpComponent},
  {path: '/using-links-pop-ups', name: 'UsingLinksPopUps', component: AboutOnlineHelpComponent},
  {path: '/assessing-recently-viewed-favorites', name: 'RecentlyViewedItems', component: AboutOnlineHelpComponent},
  {path: '/bookmarking-viewing-favorites', name: 'BookmarkingViewingFavorites', component: AboutOnlineHelpComponent},
  {path: '/changing-themes', name: 'ChangingThemes', component: AboutOnlineHelpComponent},
  {path: '/setting-default-home-page', name: 'SettingDefaultHomePage', component: AboutOnlineHelpComponent},
  {path: '/changing-page-viewing-preferences', name: 'ChangingPageViewingPreferences', component: AboutOnlineHelpComponent},
  {path: '/using-table-tools-features', name: 'UsingTableToolsFeatures', component: AboutOnlineHelpComponent},
  {path: '/viewing-entity-history', name: 'ViewingEntityHistory', component: AboutOnlineHelpComponent},
  {path: '/viewing-graphs', name: 'ViewingGraphs', component: AboutOnlineHelpComponent},
  {path: '/viewing-device-watches', name: 'ViewingDeviceWatches', component: AboutOnlineHelpComponent},
  {path: '/viewing-current-known-issues', name: 'ViewingCurrentKnownIssues', component: AboutOnlineHelpComponent},
  {path: '/enterprise-view-overview', name: 'EnterpriseViewOverview', component: AboutOnlineHelpComponent},
  {path: '/ims-dashboard-tab', name: 'IMSDashboardTab', component: AboutOnlineHelpComponent},
  {path: '/enterprise-ims-scorecard-tab', name: 'EnterpriseIMSScorecardTab', component: AboutOnlineHelpComponent},
  {path: '/map-tab', name: 'MapTab', component: AboutOnlineHelpComponent},
  {path: '/national-entitlements-tab', name: 'NationalEntitlementsTab', component: AboutOnlineHelpComponent},
  {path: '/enterprise-scorecards-tab', name: 'EnterpriseScorecardsTab', component: AboutOnlineHelpComponent},
  {path: '/market-scorecards-tab', name: 'MarketScorecardsTab', component: AboutOnlineHelpComponent},
  {path: '/cmts-scorecards-tab', name: 'CMTSScorecardsTab', component: AboutOnlineHelpComponent},
  {path: '/spectrum-analyzer-tab', name: 'SpectrumAnalyzerTab', component: AboutOnlineHelpComponent},
  {path: '/market-division-hub-overview', name: 'MarketDivisionHubOverview', component: AboutOnlineHelpComponent},
  {path: '/market-device-watch-tab', name: 'MarketDeviceWatchTab', component: AboutOnlineHelpComponent},
  {path: '/family-tree-tab', name: 'FamilyTreeTab', component: AboutOnlineHelpComponent},
  {path: '/fec-summary-tab', name: 'FECSummaryTab', component: AboutOnlineHelpComponent},
  {path: '/market-ims-scorecard-tab', name: 'MarketIMSScorecardTab', component: AboutOnlineHelpComponent},
  {path: '/market-ivr-tab', name: 'MarketIVRTab', component: AboutOnlineHelpComponent},
  {path: '/modern-firmware-report-tab', name: 'ModernFirmwareReportTab', component: AboutOnlineHelpComponent},
  {path: '/mta-battery-report-tab', name: 'MTABatteryReportTab', component: AboutOnlineHelpComponent},
  {path: '/tree-map-tab', name: 'TreeMapTab', component: AboutOnlineHelpComponent},
  {path: '/work-orders-tab', name: 'WorkOrdersTab', component: AboutOnlineHelpComponent},
  {path: '/cmts-host-overview', name: 'CMTSHostOverview', component: AboutOnlineHelpComponent},
  {path: '/status-tab', name: 'StatusTab', component: AboutOnlineHelpComponent},
  {path: '/circuits-tab', name: 'CircuitsTab', component: AboutOnlineHelpComponent},
  {path: '/cmdb-tab', name: 'CMDBTab', component: AboutOnlineHelpComponent},
  {path: '/interfaces-tab', name: 'InterfacesTab', component: AboutOnlineHelpComponent},
  {path: '/rf-interfaces-tab', name: 'RFInterfacesTab', component: AboutOnlineHelpComponent},
  {path: '/scorecard-tab', name: 'ScorecardTab', component: AboutOnlineHelpComponent},
  {path: '/tickets-tab', name: 'TicketsTab', component: AboutOnlineHelpComponent},
  {path: '/cmts-interface-overview', name: 'CMTSInterfaceOverview', component: AboutOnlineHelpComponent},
  {path: '/cmts-summary-tab', name: 'CMTSSummaryTab', component: AboutOnlineHelpComponent},
  {path: '/if-metrics-tab', name: 'IFMetricsTab', component: AboutOnlineHelpComponent},
  {path: '/statistics-tab', name: 'StatisticsTab', component: AboutOnlineHelpComponent},
  {path: '/node-view-overview', name: 'NodeViewOverview', component: AboutOnlineHelpComponent},
  {path: '/device-list-tab', name: 'DeviceListTab', component: AboutOnlineHelpComponent},
  {path: '/impact-description-tab', name: 'ImpactDescriptionTab', component: AboutOnlineHelpComponent},
  {path: '/node-ims-scorecard-tab', name: 'NodeIMSScorecardTab', component: AboutOnlineHelpComponent},
  {path: '/ping-tab', name: 'PingTab', component: AboutOnlineHelpComponent},
  {path: '/node-pnm-tab', name: 'NodePNMTab', component: AboutOnlineHelpComponent},
  {path: '/node-scorecards-tab', name: 'NodeScorecardsTab', component: AboutOnlineHelpComponent},
  {path: '/node-signal-levels-tab', name: 'NodeSignalLevelsTab', component: AboutOnlineHelpComponent},
  {path: '/account-view-overview', name: 'AccountViewOverview', component: AboutOnlineHelpComponent},
  {path: '/commercial-account-tab', name: 'CommercialAccountTab', component: AboutOnlineHelpComponent},
  {path: '/account-device-watch-tab', name: 'AccountDeviceWatchTab', component: AboutOnlineHelpComponent},
  {path: '/entitlements-tab', name: 'EntitlementsTab', component: AboutOnlineHelpComponent},
  {path: '/account-ivr-tab', name: 'AccountIVRTab', component: AboutOnlineHelpComponent},
  {path: '/provisioning-tab', name: 'ProvisioningTab', component: AboutOnlineHelpComponent},
  {path: '/account-signal-levels-tab', name: 'AccountSignalLevelsTab', component: AboutOnlineHelpComponent},
  {path: '/summary-tab', name: 'SummaryTab', component: AboutOnlineHelpComponent},
  {path: '/account-work-orders-tab', name: 'AccountWorkOrdersTab', component: AboutOnlineHelpComponent},
  {path: '/sub-account-to-master', name: 'SubAccountToMaster', component: AboutOnlineHelpComponent},
  {path: '/resetting-account-password', name: 'ResettingAccountPassword', component: AboutOnlineHelpComponent},
  {path: '/cpe-device-pages-overview', name: 'CPEDevicePagesOverview', component: AboutOnlineHelpComponent},
  {path: '/understand-cpe-relationships', name: 'UnderstandCPERelationships', component: AboutOnlineHelpComponent},
  {path: '/navigating-cpe-device-pages', name: 'NavigatingCPEDevicePages', component: AboutOnlineHelpComponent},
  {path: '/cm-summary-tab', name: 'CMSummaryTab', component: AboutOnlineHelpComponent},
  {path: '/provisioning-state', name: 'ProvisioningState', component: AboutOnlineHelpComponent},
  {path: '/dsg-state', name: 'DSGState', component: AboutOnlineHelpComponent},
  {path: '/child-devices', name: 'ChildDevices', component: AboutOnlineHelpComponent},
  {path: '/cmts-graphs-tab', name: 'CMTSGraphsTab', component: AboutOnlineHelpComponent},
  {path: '/cm-device-watch-tab', name: 'CMDeviceWatchTab', component: AboutOnlineHelpComponent},
  {path: '/cm-dhcp-tab', name: 'CMDHCPTab', component: AboutOnlineHelpComponent},
  {path: '/fec-tab', name: 'FECTab', component: AboutOnlineHelpComponent},
  {path: '/interface-map-tab', name: 'InterfaceMapTab', component: AboutOnlineHelpComponent},
  {path: '/interface-statistics-tab', name: 'InterfaceStatisticsTab', component: AboutOnlineHelpComponent},
  {path: '/logs-tab', name: 'LogsTab', component: AboutOnlineHelpComponent},
  {path: '/cm-pnm-tab', name: 'CMPNMTab', component: AboutOnlineHelpComponent},
  {path: '/cm-signal-levels-tab', name: 'CMSignalLevelsTab', component: AboutOnlineHelpComponent},
  {path: '/simple-summary-tab', name: 'SimpleSummaryTab', component: AboutOnlineHelpComponent},
  {path: '/cm-spectrum-analyzer-tab', name: 'CMSpectrumAnalyzerTab', component: AboutOnlineHelpComponent},
  {path: '/mta-overview', name: 'MTAOverview', component: AboutOnlineHelpComponent},
  {path: '/mta-summary-tab', name: 'MTASummaryTab', component: AboutOnlineHelpComponent},
  {path: '/mta-dhcp-tab', name: 'MTADHCPTab', component: AboutOnlineHelpComponent},
  {path: '/stb-overview', name: 'STBOverview', component: AboutOnlineHelpComponent},
  {path: '/sa-summary-tab', name: 'SASummaryTab', component: AboutOnlineHelpComponent},
  {path: '/stb-diagnostics-tab', name: 'STBDiagnosticsTab', component: AboutOnlineHelpComponent},
  {path: '/hydra-stb-tab', name: 'HydraSTBTab', component: AboutOnlineHelpComponent},
  {path: '/ip-stb-summary-tab', name: 'IPSTBSummaryTab', component: AboutOnlineHelpComponent},
  {path: '/motorola-summary-tab', name: 'MotorolaSummaryTab', component: AboutOnlineHelpComponent},
  {path: '/hydra-router', name: 'HydraRouter', component: AboutOnlineHelpComponent},
  {path: '/cpe-device-actions', name: 'CPEDeviceActions', component: AboutOnlineHelpComponent}
])

export class AppComponent { }